<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

<nav class="navbar  navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <!-- Navbar content -->

    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{'search'}}">Search Expense</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{'income'}}">Total Income</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{'expense'}}">Total Expense</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{'expense'}}">Last 5 Expense</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{'expense'}}">Last 5 Income</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown link
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>

  </nav>

<h1 class="text-center mt-5">Expense Tracker HomePAge</h1>
<button type="button" class="btn btn-primary"
    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
    <a class="text-dark" href="{{'search'}}">Expense Search Page</a>

</button>
<button type="button" class="btn btn-primary"
    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
    <a class="text-dark" href="{{'income'}}">Overall Income Page</a>

</button>


 <div class="container">
    <table class="table table-striped" id="dataTable">
       <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Date</th>
            <th>AttachmentPdf</th>
        </tr>
       </thead>
       <tbody>
            <!-- Table body will be filled dynamically -->
            @foreach($expenseData as $expense)
            <tr>
                <td>{{ $expense->Title }}</td>
                <td>{{ $expense->Description }}</td>
                <td>{{ $expense->Type }}</td>
                <td>{{ $expense->Amount }}</td>
                <td>{{ $expense->Date }}</td>
                <td>{{ $expense->Document }}</td>
                <td>
                    <a href="{{ route('users.expense.edit', ['userId' => $expense->id]) }}" class="btn btn-primary btn-sm edit-btn">Edit</a>

                </td>
                <td>
                    <button class="btn btn-primary btn-sm edit-btn" onclick="showDeleteConfirmation('{{ route('users.expense.destroy', ['userId' => $expense->id]) }}')">Delete</button>
                </td>

            </tr>
        @endforeach
        </tbody>

    </table>
 </div>
 <div id="pagination">
    <!-- Pagination links will be inserted here -->
    <ul class="pagination">
        <!-- Your pagination links generated by Laravel will be inserted here -->
    </ul>
</div>
<!-- Add this modal dialog at the end of your HTML body -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this expense?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <form id="deleteExpenseForm" action="" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    // Function to show delete confirmation modal
    function showDeleteConfirmation(deleteUrl) {
        var form = document.getElementById('deleteExpenseForm');
        form.action = deleteUrl;
        var modal = new bootstrap.Modal(document.getElementById('deleteConfirmationModal'));
        modal.show();
    }
</script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


</body>
</html>
